services:

# to be run with already running stack started in config-broker

################################################################################

  config-browser:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      AWS_ENDPOINT_URL: http://localstack:4566
      USE_SINGLE_INSTANCE_CACHE: true
      GRANTS_CONFIG_BROKER_API_ENDPOINT: http://grants-config-broker:3001
      CONFIG_VERSION_QUEUE_URL: http://localstack:4566/000000000000/gfr__sqs__config_browser_updates
    networks:
      - grants-framework
    volumes:
      - ./src:/home/node/src

################################################################################

networks:
  grants-framework:
    external: true
    name: grants-framework
